---
title: "RA-Instructions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{RA-Instructions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


In the following you can find the instructions we gave our able Research Assistant [Alberto Nasi](https://sites.google.com/view/albertonasi/home?authuser=0), who helped us measure city extend on digitized maps.


## How to decide whether something is part of a city or not?

We need to stick to a strict protocol to get anything useful out of this. 

1. Use mainly the "Cartes 1950" map. sometimes the arial fotos are better, or at least they can give you some good guidance about where the city ends.
1. we want to get a contiguous shape covering the city area. Often the city does *not* suddenly end. Ideally we had a grid placed over the map, and would assess the *density of built up area* in each grid cell: if there are no houses, that number is 0, if there is no unbuilt space left, that number is 100. Some maps do actually have a grid on them, so use this to make the judgement. 
1. Cutoff to be included into the city: at least 50% of all space in a grid cell is taken up by buildings/roads/etc, i.e. are *not* free open space.
1. If you make an assumption about the city limit ("I assume city x does not extend beyond that river", for example), keep that assumption in each year. All such assumptions need to be discussed.
1. Grenoble is a good example.
1. Screenshots: 
    * perform your measurement on screen. 
    * when done, make a screenshot, making sure you incldue the scale info in the bottom left corner, as well as the result of the area measurement.
    * screenshot location: all screenshots go into `LandUse/data/manual-measurement/screenshots`
    * naming convention: name each screenshot like `grenoble-EM-1.32km2.png`. 
        * `grenoble` is small caps city name
        * `EM` stands for `Etat Major`. Else we put `1950` for maps from the 1950s.
        * `1.32km2` is the measured area in square km.
1. The same procedure applies for the earlier maps, i.e the Etat Major or Cassini's maps.

## Workflow

1. Go to [geoportail](https://www.geoportail.gouv.fr/donnees/cartes-1950)
1. Search for one of th cities from below list
1. Add layer "Etat Major" (top left "cartes" switch)
1. Zoom in so entire city is visible. buildings are in red. 
1. click on the wrench top right to get tools. click on "mesures" and "mesurer une surface"
1. Delineate the city surface. clicking on the final connecting dot closes the polygon and displays the measure.
1. take a screen shot as described above
1. save as described above.
1. Add layer "Cartes 1950"
1. repeat measurement and screenshot
1. save screenshots according to naming convention above
1. Add measured areas to excel file in dropbox
