name = "LandUse"
uuid = "b17b9026-e8ed-11e9-1cc1-ff964e727923"
authors = ["Florian Oswald <florian.oswald@gmail.com>"]
version = "1.0.0"

[deps]  
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"

[compat]
julia = "1.6"


[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
