        x0=[q1(i,j),phi(i,j),r(i,j),L1(i,j),p1(i,j),S1(i,j)];    
        [x,Fval,exitflag]=fsolve('EqsysCD_um_f',x0,options);
        if exitflag<1;display('exitflag negative');return;end%if exitflag~=1;display('exitflag different from 1');return;end
        q1c(i,j)=x(1); %land price in rural sector
        phic(i,j)=x(2); %city radius
        rc(i,j)=x(3); %land rents
        L1c(i,j)=x(4); %employment in rural sector
        p1c(i,j)=x(5); %relative price of rural-sector good
        S1c(i,j)=x(6); %land used as farm sector input
        L2c(i,j)=L-L1c(i,j); %employment in rural sector
        w2c(i,j)=theta2*L2c(i,j)^eta; %wage rate urban sector with no commuting costs
        w1c(i,j)=w2c(i,j)*(1-tau*phic(i,j)); %wage rate rural sector
%        S1h(i,j)=gama/(q1(i,j)*chi1)*(w1(i,j)+r(i,j)-p1(i,j)*cbar)*L1(i,j); %rural land used for residential purposes (housing plus wasted when chi1<1).
%        c1(i,j)=nu*(1-gama)*(w2(i,j)+r(i,j)-p1(i,j)*cbar)/p1(i,j)+cbar;
%        c2(i,j)=(1-nu)*(1-gama)*(w2(i,j)+r(i,j)-p1(i,j)*cbar);
        Dc_fringe(i,j)=(chi2*q1c(i,j)/gama2);
        Dc_m(i,j)=(chi2*q1c(i,j)/gama2)*((w2c(i,j)*(1-tau*phim)+rc(i,j)-p1c(i,j)*cbar))^(1/gama2-1)/((w2c(i,j)*(1-tau*phic(i,j))+rc(i,j)-p1c(i,j)*cbar)^(1/gama2));
        Dc_cbd(i,j)=(chi2*q1c(i,j)/gama2)*((w2c(i,j)+rc(i,j)-p1c(i,j)*cbar))^(1/gama2-1)/((w2c(i,j)*(1-tau*phic(i,j))+rc(i,j)-p1c(i,j)*cbar)^(1/gama2));
